[package]
name = "surrealfs-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
surrealfs-types = { workspace = true }
surrealfs-kernel = { workspace = true }
surrealfs-store = { workspace = true }
fs4 = { workspace = true }
tokio = { workspace = true }
